project:
  type: website
  output-dir: docs

website:
  title: "Hyun zuu"
  navbar:
    left:
      - href: index.qmd #qnd 하나하나가 페이지
        text: Home
      - href: about.qmd
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

